### ISSUE TITLE
unsuported board

### ISSUE THREAD

**Issue by kashiik** [SensorsIot/ESP32-Cameras-and-MEMS-Microphones#1]
Hello,
thank you for your example. it works just great :)

I found new board type.
its extended of TT-GO white wit BME280.
pinout look like this:
#define PWDN_GPIO_NUM     -1
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM     32
#define SIOD_GPIO_NUM     13
#define SIOC_GPIO_NUM     12

#define Y9_GPIO_NUM       39
#define Y8_GPIO_NUM       36
#define Y7_GPIO_NUM       23
#define Y6_GPIO_NUM       18
#define Y5_GPIO_NUM       15
#define Y4_GPIO_NUM       4
#define Y3_GPIO_NUM       14
#define Y2_GPIO_NUM       5
#define VSYNC_GPIO_NUM    27
#define HREF_GPIO_NUM     25
#define PCLK_GPIO_NUM     19

**Comment by SensorsIot** [comment]
Thank you!
